version: '3.4'

services:
  ravendb:
    image: ravendb/ravendb:5.3.1-ubuntu.20.04-x64
    volumes:
      - ravendb-config:/opt/RavenDB/config
      - ravendb-data:/opt/RavenDB/Server/RavenData
    ports:
      - 8080:8080
      - 38888:38888
    environment:
      - RAVEN_Setup_Mode=None

  chocshop2:
    image: ${DOCKER_REGISTRY-}chocshop2
    depends_on:
      - ravendb
    build:
      context: .
      dockerfile: ChocShop2/Dockerfile

volumes:
  ravendb-config:
  ravendb-data: